apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  #googleCloudBuild:
  #    projectId: ticketing-299514
  artifacts:
    - image: denizgirginer8/ticket-auth #us.gcr.io/ticketing-299514/auth
      context: AuthApi # docker build context folder
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.cs'
            dest: .
    - image: denizgirginer8/tickets #us.gcr.io/ticketing-299514/tickets
      context: TicketsApi # docker build context folder
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.cs'
            dest: .
    - image: denizgirginer8/orders #us.gcr.io/ticketing-299514/orders
      context: OrdersApi # docker build context folder
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.cs'
            dest: .
    - image: denizgirginer8/expiration #us.gcr.io/ticketing-299514/orders
      context: ExpirationSvc # docker build context folder
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.cs'
            dest: .
    - image: denizgirginer8/payments #us.gcr.io/ticketing-299514/orders
      context: PaymentsApi # docker build context folder
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.cs'
            dest: .
    - image: denizgirginer8/client 
      context: Client 
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
          - src: '**/*.css'
            dest: .
          - src: '**/*.html'
            dest: .