apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-demo-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: dotnet-demo
  template:
    metadata:
      labels:
        app: dotnet-demo
    spec:
      containers:
        - name: dotnet-demo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-demo-mongo-service
spec:
  selector:
    app: dotnet-demo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017